### ISSUE TITLE
@NiceSapien please provide commands to run this website in emulator or something I always get error while I run this website

### ISSUE THREAD

**Issue by NiceSapien** [NiceSapien/swpro-website#14]
@NiceSapien please provide commands to run this website in emulator or something I always get error while I run this website

_Originally posted by @TechnicalStudioDevelopers in https://github.com/NiceSapien/swpro-website/pull/13#issuecomment-1407893371_

**Comment by NiceSapien** [comment]
> docusaurus: not found
> error Command failed with exit code 127
@TechnicalStudioDevelopers 
Please read the README.md's contributing guide always before contributing. 
1. Always push in the Dev branch(sorry i didn't mention it there).
2. It is clearly stated,
```cmd
npm install
npm start
```

Please don't consider me rude or smth, i just wanted to help. If you still face problems, please comment down.

**Comment by TechnicalStudioDevelopers** [comment]
> > docusaurus: not found
> > error Command failed with exit code 127
> > @TechnicalStudioDevelopers
> > Please read the README.md's contributing guide always before contributing.
> 
> 1. Always push in the Dev branch(sorry i didn't mention it there).
> 2. It is clearly stated,
> 
> ```batchfile
> npm install
> npm start
> ```
> 
> Please don't consider me rude or smth, i just wanted to help. If you still face problems, please comment down.

2.When I call npm start it shows me 
`docusaurus: not found`

**Comment by NiceSapien** [comment]
Did you try `npm install` first?

**Comment by TechnicalStudioDevelopers** [comment]
No I used yarn

**Comment by NiceSapien** [comment]
Try `yarn start` then

**Comment by TechnicalStudioDevelopers** [comment]
> Try `yarn start` then

Its worked that's why I created pull request

**Comment by NiceSapien** [comment]
Alright. If you use yarn for installing, then use it for building and testing too. If you use npm for installing, then use npm.

Closing the issue now.
