### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by TechnicalStudioDeveloper** [NiceSapien/swpro-website#19]
This repository should contain Discussion section.

**Comment by TechnicalStudioDevelopers** [comment]
How to do that :
When use click on `Get Started ` so the page will scroll to the `Get Started` heading coded as :

# Get Started

**Comment by TechnicalStudioDevelopers** [comment]
@NiceSapien I want to change email to Name as in last edited by
![img](https://user-images.githubusercontent.com/96680248/216048450-26e4b08f-8f65-463c-9333-e47a734acb18.jpg)

How can I?

**Comment by NiceSapien** [comment]
> @NiceSapien I want to change email to Name as in last edited by ![img](https://user-images.githubusercontent.com/96680248/216048450-26e4b08f-8f65-463c-9333-e47a734acb18.jpg)
> 
> How can I?

IT WILL CHANGE AUTOMATICALLY IN PRODUCTION I GUESS.

**Comment by TechnicalStudioDevelopers** [comment]
> > @NiceSapien I want to change email to Name as in last edited by ![img](https://user-images.githubusercontent.com/96680248/216048450-26e4b08f-8f65-463c-9333-e47a734acb18.jpg)
> > How can I?
> 
> IT WILL CHANGE AUTOMATICALLY IN PRODUCTION I GUESS.

I fixed it my replacing email to name

**Comment by NiceSapien** [comment]
Fixed I guess.
