### ISSUE TITLE
Misleading

### ISSUE THREAD

**Issue by ReduxFlakes** [NiceSapien/swpro-website#29]
This should be removed, you are treating this as if its from the official (mod) team even though you are not even part of the team. This is very misleading to new users as well with most content being taken from the mod repo without attribution or source and this repo is using a different license than the official one making this situation even worst. 
Also, stop being toxic with that kid behavior with the official mod team, its kinda stupid of your part. 
Or you give permission to the developers or this will be reported as impersonation.

**Comment by ReduxFlakes** [comment]
Oh no your website is literally a carbon copy of [Brittany Chiang](https://brittanychiang.com/) portfolio, now thats what I call a *"developer"*

**Comment by TechnicalStudioDeveloper** [comment]
@ReduxFlakes In my sense this repository should me transferred to Sketchware/swpro-website to be more visible as official website..

**Comment by TechnicalStudioDeveloper** [comment]
@ReduxFlakes mention NiceSapien because he is not watching this repo.

**Comment by TechnicalStudioDeveloper** [comment]
@NiceSapien

**Comment by nicesapien-too** [comment]
> This should be removed, you are treating this as if its from the official (mod) team even though you are not even part of the team. This is very misleading to new users as well with most content being taken from the mod repo without attribution or source and this repo is using a different license than the official one making this situation even worst. Also, stop being toxic with that kid behavior with the official mod team, its kinda stupid of your part. Or you give permission to the developers or this will be reported as impersonation.

When did i treat this as official? And which content is being taken from mod repo huh? And this is my project i can set my own license + when this was official jbk told me to set this license. And you arent even in the team and where is kid behaviour? You cant report this because swpro is also illegal.

**Comment by TechnicalStudioDeveloper** [comment]
> > This should be removed, you are treating this as if its from the official (mod) team even though you are not even part of the team. This is very misleading to new users as well with most content being taken from the mod repo without attribution or source and this repo is using a different license than the official one making this situation even worst. Also, stop being toxic with that kid behavior with the official mod team, its kinda stupid of your part. Or you give permission to the developers or this will be reported as impersonation.
> 
> When did i treat this as official? And which content is being taken from mod repo huh? And this is my project i can set my own license + when this was official jbk told me to set this license. And you arent even in the team and where is kid behaviour? You cant report this because swpro is also illegal.

Cool down bro!!
In my opinion this repo has less views and this repo is not much visible.This repo should be in Sketchware pro as in image.
![Screenshot_2023-02-27-19-00-27-494_com android chrome](https://user-images.githubusercontent.com/96680248/221576566-92a38c49-d4fd-46d3-9bdf-c32d2d07b95f.jpg)
This would be great if this repo transferred there because app open source app have their website in same account.

**Comment by NiceSapien** [comment]
> > > This should be removed, you are treating this as if its from the official (mod) team even though you are not even part of the team. This is very misleading to new users as well with most content being taken from the mod repo without attribution or source and this repo is using a different license than the official one making this situation even worst. Also, stop being toxic with that kid behavior with the official mod team, its kinda stupid of your part. Or you give permission to the developers or this will be reported as impersonation.
> > 
> > 
> > When did i treat this as official? And which content is being taken from mod repo huh? And this is my project i can set my own license + when this was official jbk told me to set this license. And you arent even in the team and where is kid behaviour? You cant report this because swpro is also illegal.
> 
> Cool down bro!! In my opinion this repo has less views and this repo is not much visible.This repo should be in Sketchware pro as in image. ![Screenshot_2023-02-27-19-00-27-494_com android chrome](https://user-images.githubusercontent.com/96680248/221576566-92a38c49-d4fd-46d3-9bdf-c32d2d07b95f.jpg) This would be great if this repo transferred there because app open source app have their website in same account.

Bro did you know this website used to be official but it's not anymore. See https://GitHub.com/sketchware-pro/website it used to be there earlier

**Comment by TechnicalStudioDeveloper** [comment]
> Bro did you know this website used to be official but it's not anymore. See https://GitHub.com/sketchware-pro/website it used to be there earlier
But why???

**Comment by TechnicalStudioDeveloper** [comment]
> Bro did you know this website used to be official but it's not anymore. See https://github.com/sketchware-pro/website it used to be there earlier

But Why?

**Comment by NiceSapien** [comment]
> > Bro did you know this website used to be official but it's not anymore. See https://github.com/sketchware-pro/website it used to be there earlier
> 
> But Why?

Because the official modders didn't want it. Some links are still available in Sketchware Pro app though.

**Comment by NiceSapien** [comment]
I've talked to people in swpro server and they said this website is fine and ReduxFlakes is dumb. Closing issue

**Comment by ReduxFlakes** [comment]
> I've talked to people in swpro server and they said this website is fine and ReduxFlakes is dumb. Closing issue

swpro server didn't say I was dumb. swpro server didn't say I was dumb. Anyway, you asked where the kid behavior is, and there you have it, resolving an unresolved issue because you know I'm right and your website is still a carbon copy of [Brittany Chiang's website](https://brittanychiang.com/).

**Comment by NiceSapien** [comment]
> > I've talked to people in swpro server and they said this website is fine and ReduxFlakes is dumb. Closing issue
> 
> swpro server didn't say I was dumb. swpro server didn't say I was dumb. Anyway, you asked where the kid behavior is, and there you have it, resolving an unresolved issue because you know I'm right and your website is still a carbon copy of [Brittany Chiang's website](https://brittanychiang.com/).

And it's mentioned there you blindo.
